config/routes.rb
Rails.application.routes.draw do
  
  resources :friendships
  devise_for :users , :controllers => { registrations: 'registrations' }
  resources :users 
 root 'users#index'
 post "users/current/destroy"
  get 'users/index' => 'users#index'

  
   
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :user
belongs_to :friend, :class_name => "User"
 def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count<1
  end
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :friendships 
has_many :friends, :through => :friendships



has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  scope :friend_with, ->( other ) do
    other = other.id if other.is_a?( User )
    where( '(friendships.user_id = users.id AND friendships.friend_id = ?) OR (friendships.user_id = ? AND friendships.friend_id = users.id)', other, other ).includes( :frienships )
  end
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count<1
  end
  def friend_with?( other )
    User.where( id: id ).friend_with( other ).any?
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
   

  def create
  @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  if @friendship.save
    flash[:notice] = "Added friend."
    redirect_to root_url
  else
    flash[:error] = "Unable to add friend."
    redirect_to root_url
  end
end

 

def destroy

 
  @friendship = Friendship.find(params[:id])
  @friendship.destroy
  flash[:notice] = "Removed friendship."
  redirect_to current_user
end

  def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :create, :destroy,:current)
    end
 def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count<1
  end
  private

  def check_friendship
    redirect_to( current_user, alert: 'Already a friend' ) if current_user.friend_with?( params[ :friend_id ] )
  end
 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :surname, :phone, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :surname, :phone, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
   @users=User.all
   @user = current_user
 end
 def current
 @user = current_user
 end
 def show
  @t=0
  @user = User.find(params[:id])
  
 end
 
  def sign_in
  end
 def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count<1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br>
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= friendship.friend.username  %>
</p>


<>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friends</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>

<nav  class="navbar navbar-inverse">
  <div  class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/users">
        LISTA OSÓB
      </a>
    </div>
 
   </div>
 </nav>
<ul class="navbar navbar-nav navbar-left">

  
</ul>   


<%= yield %>



</body>
</html>

app/views/users/index.html.erb
 <% if user_signed_in? %>
 <h2>Jesteś zalogowany jako:  <font color="green"><%=h @user.email %></font><% @users.each do |user| %><% if current_user == user %>  <%= link_to 'Mój profil', user %><% else %><%end%><%end%></h2><font color="green"><h4><li><%= link_to "Wyloguj",destroy_user_session_url,:method =>'delete' %></li></h4></font>
  
 <font color="blue"><h1> LISTA OSÓB</h1></font>
<br>
 <% @users.each do |user| %>
<% if current_user == user %>
  
<% else %>
   <h3>- <%= user.email %>
<%= link_to 'Szczegóły', user %>

 
<% if current_user.not_friends_with?(user.id) %> 
  <%= link_to "Dodaj przyjaciela", friendships_path(:friend_id => user), :method => :post %> 
  <%else%>
 Już jestescie przyjaciółmi!!
<%end%>
<br></h4>
<%end%>
<%end%>
<% else %>
<font color="green"><h4><li><%=link_to "Zaloguj", new_user_session_url%></li></h4></font>
 <% end %>

<% if user_signed_in? %>
<%else%>
<a href="users/sign_up">Zarejestruj się</a>
<%end%>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
Witaj <h3> <font color="green"><%=h @user.email %></font> Twoje Dane:  </h3> 
Imie: <strong><%=h @user.username %></strong>
Nazwisko:<strong> <%=h @user.surname %></strong>
telefon :<strong> <%= @user.phone %></strong><font color="green"><h4><li><%= link_to "Wyloguj",destroy_user_session_url,:method =>'delete' %></li></h4></font> <p><a href="edit">Edytuj dane</a></p>
<p><button class="b1"><%= link_to "Dodaj przyjaciela", users_path %></button></p>


<h2>Twoi przyjaciele:</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>email</th>
      <th>numer telefonu</th>
      <th>akcja</th>
    </tr>
  </thead>
  <tbody>
   <% for friendship in @user.friendships %>
    <tr>
      <th scope="row"><%= @t=@t+1 %></th>
      <td><% if friendship.friend.username.present? %><%=h friendship.friend.username.gsub(/\s+/, '').capitalize %> <% else%> ---<%end%></td>
      <td><% if friendship.friend.surname.present? %><%=h friendship.friend.surname.gsub(/\s+/, '').capitalize %><% else%> ---<%end%></td>
      <td><%=h friendship.friend.email %></td>
       <td><%=h friendship.friend.phone %></td>
      <td> <%= link_to "Usuń", friendship, :method => :delete %>, <a href="<%=h friendship.friend.id %>">Szczegóły</a></td>
    </tr>

    <% end %>
  </tbody>
</table>


<h2>Do grona przyjaciół dodali Cie:</h2>

<%else%>
<h3> <font color="green"><%=h @user.email %></font> Dane osoby: </h3>
Imie: <strong><%=h @user.username %></strong>
Nazwisko:<strong> <%=h @user.surname %></strong>
telefon :<strong> <%= @user.phone %></strong>
<p><%= link_to "Szukaj przyjaciół", users_path %></p>


<h2>Przyjaciele osoby:</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>email</th>
      <th>numer telefonu</th>
      <th>akcja</th>
    </tr>
  </thead>
  <tbody>
   <% for friendship in @user.friendships %>
    <tr>
      <th scope="row"><%= @t=@t+1 %></th>
      <td><% if friendship.friend.username.present? %><%=h friendship.friend.username.gsub(/\s+/, '').capitalize %> <% else%> ---<%end%></td>
      <td><% if friendship.friend.surname.present? %><%=h friendship.friend.surname.gsub(/\s+/, '').capitalize %><% else%> ---<%end%></td>
      <td><%=h friendship.friend.email %></td>
       <td><%=h friendship.friend.phone %></td>
      <td>  <a href="<%=h friendship.friend.id %>">Szczegóły</a></td>
    </tr>

    <% end %>
  </tbody>
</table>


<h2>Do grona przyjaciół dodali osobe:</h2>

 <%end%>
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>email</th>
      <th>numer telefonu</th>
      <th>akcja</th>
    </tr>
  </thead>
  <tbody>
   <% for user in @user.inverse_friends %>
    <tr>
      <th scope="row"><%= @t=@t+1 %></th>
      <td> <% if user.username.present? %><%=h user.username.gsub(/\s+/, '').capitalize %> <% else%> ---<%end%></td>
      <td><% if user.surname.present? %><%=h user.surname.gsub(/\s+/, '').capitalize %> <% else%> ---<%end%></td>
      <td><%=h user.email %></td>
       <td><%=h user.phone %></td>
      <td>  <a href="<%=h user.id %>">Szczegóły</a></td>
    </tr>

    <% end %>
  </tbody>
</table>
 